version: '2.2'

services: 
  salt-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    volumes:
      - ./salt:/srv/salt
      - ./pillar:/srv/pillar
      - ./test:/srv/test
  salt-minion:
    build:
      context: .
      dockerfile: Dockerfile.minion
    depends_on:
      - salt-master
    scale: 2
